Repository uasoft-indonesia/badaso-graphql-module, pull requests merged in 2021-06, with the labels that each got.

#1 Feature/graphql customize
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/autolabeler.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
  .gitignore
  .styleci.yml
  CONTRIBUTING.md
  README.md
  composer.json
  src/BadasoGraphQL/AccommodateBadasoGraphQL.php
  src/BadasoGraphQL/Mutation/ExampleMutation.php
  src/BadasoGraphQL/Query/ExampleQuery.php
  src/BadasoGraphQL/Type/ExampleType.php
  src/BadasoGraphqlModule.php
  src/Commands/BadasoGraphqlSetup.php
  src/Config/badaso-graphql.php
  src/Config/graphql-playground.php
  src/Controllers/BadasoGraphqlController.php
  src/Controllers/Controller.php
  src/Core/GenerateGraphql.php
  src/Core/GenerateMutationGraphql.php
  src/Core/GenerateQueryGraphql.php
  src/Facades/BadasoGraphqlModule.php
  src/Interfaces/AccommodateHandleInterface.php
  src/Interfaces/GenerateMutationInterface.php
  src/Interfaces/GenerateQueryInterface.php
  src/Interfaces/GenerateTypeInterface.php
  src/Middleware/BadasoGraphQLMiddleware.php
  src/Providers/BadasoGraphqlModuleServiceProvider.php
  src/Routes/graphql.php
  src/Seeder/GraphQL/GraphQLFixedMenuItemSeeder.php
  src/Seeder/GraphQL/GraphQLMenusSeeder.php
  src/Seeder/GraphQL/GraphQLModuleSeeder.php
  src/Seeder/GraphQL/GraphQLPermissionsSeeder.php
  src/Seeder/GraphQL/GraphQLRolePermissionsSeeder.php
  src/Traits/PermissionForCRUDTrait.php
  src/resources/js/api/index.js
  src/resources/js/components/index.js
  src/resources/js/lang/index.js
  src/resources/js/lang/modules/en.js
  src/resources/js/lang/modules/id.js
  src/resources/js/pages/graphql/browse.vue
  src/resources/js/pages/index.vue
  src/resources/js/router/routes.js
  src/resources/js/store/badaso.js
Labels: feature

#5 Apply fixes from StyleCI
  src/Core/GenerateGraphql.php
  src/Seeder/GraphQL/GraphQLRolePermissionsSeeder.php
  src/Traits/PermissionForCRUDTrait.php
Labels: backend

#6 Merge develop to main
  README.md
  composer.json
Labels: dependencies

#8 Apply fixes from StyleCI
  src/Core/GenerateGraphql.php
  src/Seeder/GraphQL/GraphQLRolePermissionsSeeder.php
  src/Traits/PermissionForCRUDTrait.php
Labels: backend

#10 Merge develop to main
  src/Commands/BadasoGraphqlSetup.php
  src/Providers/BadasoGraphqlModuleServiceProvider.php
  src/Seeder/GraphQL/GraphQLFixedMenuItemSeeder.php
  src/Seeder/GraphQL/GraphQLMenusSeeder.php
  src/Seeder/GraphQL/GraphQLModuleSeeder.php
  src/Seeder/GraphQL/GraphQLPermissionsSeeder.php
  src/Seeder/GraphQL/GraphQLRolePermissionsSeeder.php
Labels: backend

#12 Apply fixes from StyleCI
  src/Seeder/GraphQL/GraphQLRolePermissionsSeeder.php
Labels: backend

#11 Enhancement/upgrade laravel 8
  composer.json
  src/Seeder/GraphQL/GraphQLFixedMenuItemSeeder.php
  src/Seeder/GraphQL/GraphQLMenusSeeder.php
  src/Seeder/GraphQL/GraphQLModuleSeeder.php
  src/Seeder/GraphQL/GraphQLPermissionsSeeder.php
  src/Seeder/GraphQL/GraphQLRolePermissionsSeeder.php
Labels: backend, dependencies

#13 Merge develop to main
  src/Seeder/GraphQL/GraphQLFixedMenuItemSeeder.php
  src/Seeder/GraphQL/GraphQLMenusSeeder.php
  src/Seeder/GraphQL/GraphQLModuleSeeder.php
  src/Seeder/GraphQL/GraphQLPermissionsSeeder.php
  src/Seeder/GraphQL/GraphQLRolePermissionsSeeder.php
Labels: backend

#15 Apply fixes from StyleCI
  src/Controllers/BadasoGraphqlController.php
  src/Core/GenerateGraphql.php
  src/Core/GenerateMutationGraphql.php
  src/Core/GenerateQueryGraphql.php
  src/Core/Query/MetaQuery.php
  src/Core/Type/MetaType.php
Labels: backend

#14 Add Meta Query
  src/Core/GenerateGraphql.php
  src/Core/GenerateMutationGraphql.php
  src/Core/Mutation/MetaMutation.php
  src/Core/Query/MetaQuery.php
  src/Core/Type/MetaType.php
Labels: backend, feature
