Repository uasoft-indonesia/badaso-graphql-module, pull requests merged in 2021-07, with the labels that each got.

#17 [Badaso v1] update name
  CONTRIBUTING.md
  README.md
  src/Seeder/GraphQL/BadasoGraphQLFixedMenuItemSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLMenusSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLModuleSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLPermissionsSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLRolePermissionsSeeder.php
  src/Seeder/GraphQL/GraphQLModuleSeeder.php
  src/resources/js/api/modules/readme.md
Labels: backend, bugfix

#19 [Badaso v2] Bugfix/v2/update name
  CONTRIBUTING.md
  README.md
  composer.json
  src/Core/GenerateGraphql.php
  src/Core/GenerateMutationGraphql.php
  src/Core/Mutation/MetaMutation.php
  src/Core/Query/MetaQuery.php
  src/Core/Type/MetaType.php
  src/Seeder/GraphQL/BadasoGraphQLFixedMenuItemSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLMenusSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLModuleSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLPermissionsSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLRolePermissionsSeeder.php
  src/Seeder/GraphQL/GraphQLModuleSeeder.php
  src/resources/js/api/modules/readme.md
Labels: backend, bugfix, dependencies

#20 Prepare release 2.0.0-rc.2
  CONTRIBUTING.md
  README.md
  composer.json
  src/Core/GenerateGraphql.php
  src/Core/GenerateMutationGraphql.php
  src/Core/Mutation/MetaMutation.php
  src/Core/Query/MetaQuery.php
  src/Core/Type/MetaType.php
  src/Seeder/GraphQL/BadasoGraphQLFixedMenuItemSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLMenusSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLModuleSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLPermissionsSeeder.php
  src/Seeder/GraphQL/BadasoGraphQLRolePermissionsSeeder.php
  src/Seeder/GraphQL/GraphQLModuleSeeder.php
  src/resources/js/api/modules/readme.md
Labels: backend, dependencies

#22 Fix composer.json
  composer.json
Labels: dependencies

#25 Apply fixes from StyleCI
  src/Seeder/GraphQL/BadasoGraphQLRolePermissionsSeeder.php
Labels: backend

#24 [Badaso v1] updated composer.json, contribute.md, and readme.md
  CONTRIBUTING.md
  README.md
Labels: backend, dependencies

#26 [Badaso v2] updated composer.json, contribute.md, and readme.md
  CONTRIBUTING.md
  README.md
Labels: dependencies
